Repository PetJournal/petjournal.api, pull requests merged in 2023-05, with the labels that each got.

#8 docs: fixes docker compose command
  README.md
Labels: Documentation

#17 Refactor/guardian register
  src/application/controllers/signup.ts
  src/application/errors/conflict-guardian-error.ts
  src/application/errors/index.ts
  src/application/errors/server-error.ts
  src/application/helpers/http.ts
  src/data/protocols/add-guardian-repository.ts
  src/data/protocols/logger-error-repository.ts
  src/domain/use-cases/add-guardian.ts
  src/infra/repos/postgresql/guardian-account-repository.ts
  src/infra/repos/postgresql/logger-repository.ts
  src/infra/repos/postgresql/prisma/migrations/20230422140604_init/migration.sql
  src/infra/repos/postgresql/prisma/migrations/20230505145253_log_error/migration.sql
  src/infra/repos/postgresql/prisma/schema.prisma
  src/main/adapters/express-route-adapter.ts
  src/main/decorators/logger.ts
  src/main/docs/components.ts
  src/main/docs/components/conflict.ts
  src/main/docs/components/index.ts
  src/main/docs/paths/signup-path.ts
  src/main/docs/schemas.ts
  src/main/docs/schemas/guardian-schema.ts
  src/main/docs/schemas/index.ts
  src/main/factories/controllers/signup-controller-factory.ts
  tests/application/controllers/signup.spec.ts
  tests/data/use-cases/db-add-guardian.spec.ts
  tests/helpers/prisma-helper.ts
  tests/infra/repos/postgresql/guardian-account.spec.ts
  tests/infra/repos/postgresql/logger-repository.spec.ts
  tests/main/decorators/logger.spec.ts
  tests/main/routes/signup-routes.test.ts
Labels: BackEnd Team

#14 Feature/forget password
  .env.example
  package-lock.json
  package.json
  src/application/controllers/forget-password.ts
  src/application/errors/index.ts
  src/application/errors/not-found-error.ts
  src/data/protocols/guardian/index.ts
  src/data/protocols/guardian/load-guardian-by-email-repository.ts
  src/data/protocols/guardian/save-token-repository.ts
  src/data/protocols/recovery-password/index.ts
  src/data/protocols/recovery-password/token-generator.ts
  src/data/use-cases/db-forget-password.ts
  src/data/use-cases/forget-password-token-generation.ts
  src/data/use-cases/index.ts
  src/domain/use-cases/email-service.ts
  src/domain/use-cases/forget-password.ts
  src/domain/use-cases/index.ts
  src/domain/use-cases/load-guardian-by-email.ts
  src/domain/use-cases/save-token.ts
  src/infra/node-mailer-adapter.ts
  src/infra/repos/postgresql/guardian-account-repository.ts
  src/infra/repos/postgresql/prisma/migrations/20230506162729_add_forget_password_token_field/migration.sql
  src/infra/repos/postgresql/prisma/schema.prisma
  src/main/config/env.ts
  src/main/docs/index.ts
  src/main/docs/paths.ts
  src/main/docs/paths/forget-password-path.ts
  src/main/docs/paths/index.ts
  src/main/docs/schemas.ts
  src/main/docs/schemas/forget-password-schema.ts
  src/main/docs/schemas/index.ts
  src/main/factories/controllers/forget-password-factory.ts
  src/main/routes/forget-password-routes.ts
  tests/src/application/controllers/forget-password.spec.ts
  tests/src/data/use-cases/db-add-guardian.spec.ts
  tests/src/data/use-cases/db-forget-password.spec.ts
  tests/src/data/use-cases/forget-password-token-generator.spec.ts
  tests/src/infra/node-mailer-adapter.spec.ts
  tests/src/infra/repos/postgresql/guardian-account.spec.ts
  tests/src/infra/repos/postgresql/logger-repository.spec.ts
  tests/src/main/routes/forget-password-routes.test.ts
  tests/utils/mocks/entities.mocks.ts
  tests/utils/mocks/request.mocks.ts
  tests/utils/types/guardian.type.ts
  yarn.lock
Labels: BackEnd Team, Feature

#18 Refactor/forget password
  src/application/controllers/forget-password.ts
  src/data/protocols/recovery-password/index.ts
  src/data/protocols/recovery-password/token-generator.ts
  src/domain/use-cases/load-guardian-by-email.ts
  src/domain/use-cases/save-token.ts
  src/main/factories/controllers/forget-password-factory.ts
  tests/src/application/controllers/forget-password.spec.ts
  tests/src/data/use-cases/db-forget-password.spec.ts
  tests/src/main/decorators/logger.spec.ts
  tests/utils/mocks/request.mocks.ts
Labels: BackEnd Team
