Repository PetJournal/petjournal.api, pull requests merged in 2025-05, with the labels that each got.

#75 Feature/create schedule table
  src/infra/repos/postgresql/prisma/migrations/20250422075715_create_scheduler_table/migration.sql
  src/infra/repos/postgresql/prisma/migrations/20250422075816_create_event_table/migration.sql
  src/infra/repos/postgresql/prisma/schema.prisma
Labels: BackEnd Team, Feature

#77 refactor: rename scheduler directory
  src/data/use-cases/schedule/tag/db-add-tag.ts
  src/data/use-cases/schedule/tag/db-delete-tag-by-id.ts
  src/data/use-cases/schedule/tag/db-load-tag-by-id.ts
  src/data/use-cases/schedule/tag/db-load-tags.ts
  src/data/use-cases/schedule/tag/db-update-tag.ts
  src/domain/use-cases/scheduler/tag/add-tag.ts
  src/domain/use-cases/scheduler/tag/delete-tag-by-id.ts
  src/domain/use-cases/scheduler/tag/index.ts
  src/domain/use-cases/scheduler/tag/load-tag-by-id.ts
  src/domain/use-cases/scheduler/tag/load-tags.ts
  src/domain/use-cases/scheduler/tag/update-tag.ts
  tests/src/data/use-cases/schedule/tag/db-add-tag.spec.ts
  tests/src/data/use-cases/schedule/tag/db-delete-tag-by-id.spec.ts
  tests/src/data/use-cases/schedule/tag/db-load-tag-by-id.spec.ts
  tests/src/data/use-cases/schedule/tag/db-load-tags.spec.ts
  tests/src/data/use-cases/schedule/tag/db-update-tag.spec.ts
Labels: Refactor

#78 Feature/add tag controller
  src/application/controllers/scheduler/index.ts
  src/application/controllers/scheduler/tag/add-tag.ts
  src/application/controllers/scheduler/tag/index.ts
  src/data/use-cases/schedule/tag/db-add-tag.ts
  src/domain/use-cases/index.ts
  src/domain/use-cases/scheduler/index.ts
  src/domain/use-cases/scheduler/tag/add-tag.ts
  tests/src/application/controllers/scheduler/tag/add-tag.spec.ts
  tests/src/data/use-cases/schedule/tag/db-add-tag.spec.ts
  tests/utils/mocks/request.mock.ts
  tests/utils/stubs/use-case.stub.ts
  tests/utils/types/request.type.ts
Labels: BackEnd Team, Feature

#79 Feature/load tag by id controller
  src/application/controllers/index.ts
  src/application/controllers/scheduler/tag/index.ts
  src/application/controllers/scheduler/tag/load-tag-by-id.ts
  tests/src/application/controllers/scheduler/tag/load-tag-by-id.spec.ts
  tests/utils/stubs/use-case.stub.ts
Labels: BackEnd Team, Feature

#80 Feature/load tags controller
  src/application/controllers/scheduler/tag/index.ts
  src/application/controllers/scheduler/tag/load-tags.ts
  tests/src/application/controllers/scheduler/tag/load-tags.spec.ts
  tests/utils/stubs/use-case.stub.ts
Labels: BackEnd Team, Feature

#81 Feature/delete tag by id controller
  src/application/controllers/scheduler/tag/delete-tag-by-id.ts
  src/application/controllers/scheduler/tag/index.ts
  tests/src/application/controllers/scheduler/tag/delete-tag-by-id.spec.ts
  tests/utils/stubs/use-case.stub.ts
Labels: BackEnd Team, Feature

#82 Feature/update tag controller
  src/application/controllers/scheduler/tag/index.ts
  src/application/controllers/scheduler/tag/update-tag.ts
  tests/src/application/controllers/scheduler/tag/update-tag.spec.ts
  tests/utils/stubs/use-case.stub.ts
Labels: BackEnd Team, Feature

#83 Feature/tag validations
  src/application/controllers/index.ts
  src/application/controllers/scheduler/index.ts
  src/application/controllers/scheduler/tag/add-tag.ts
  src/application/controllers/scheduler/tag/delete-tag-by-id.ts
  src/application/controllers/scheduler/tag/index.ts
  src/application/controllers/scheduler/tag/load-tag-by-id.ts
  src/application/controllers/scheduler/tag/load-tags.ts
  src/application/controllers/scheduler/tag/update-tag.ts
  src/application/validation/protocols/color-validator.ts
  src/application/validation/protocols/index.ts
  src/application/validation/validators/color-validation.ts
  src/application/validation/validators/index.ts
  src/data/use-cases/schedule/tag/db-add-tag.ts
  src/domain/use-cases/index.ts
  src/domain/use-cases/scheduler/index.ts
  src/domain/use-cases/scheduler/tag/add-tag.ts
  src/infra/validators/color-validator-adapter.ts
  src/infra/validators/index.ts
  tests/src/application/controllers/scheduler/tag/add-tag.spec.ts
  tests/src/application/controllers/scheduler/tag/delete-tag-by-id.spec.ts
  tests/src/application/controllers/scheduler/tag/load-tag-by-id.spec.ts
  tests/src/application/controllers/scheduler/tag/load-tags.spec.ts
  tests/src/application/controllers/scheduler/tag/update-tag.spec.ts
  tests/src/application/validation/validators/color-validation.spec.ts
  tests/src/data/use-cases/schedule/tag/db-add-tag.spec.ts
  tests/src/infra/validators/color-validator-adapter.spec.ts
  tests/utils/mocks/request.mock.ts
  tests/utils/stubs/use-case.stub.ts
  tests/utils/stubs/validation.stub.ts
  tests/utils/types/request.type.ts
Labels: BackEnd Team, Feature

#85 fix: import dotenv in PrismaHelper
  src/infra/repos/postgresql/prisma/generated/client.ts
  src/infra/repos/postgresql/prisma/generated/internal/class.ts
  src/infra/repos/postgresql/prisma/generated/internal/prismaNamespace.ts
  src/infra/repos/postgresql/prisma/generated/models.ts
  src/infra/repos/postgresql/prisma/generated/models/Pet.ts
  src/infra/repos/postgresql/prisma/generated/models/Tag.ts
  src/infra/repos/postgresql/prisma/migrations/20250520205843_/migration.sql
  src/infra/repos/postgresql/prisma/migrations/migration_lock.toml
  tests/helpers/prisma-helper.ts
Labels: Bug, BackEnd Team
